import type { RouteRecordRaw } from 'vue-router'

import AuthUnavailableView from '@/views/error/AuthUnavailableView.vue'

export const routes: RouteRecordRaw[] = [
  { path: '/login', name: 'Login', component: () => import('@/views/auth/LoginView.vue'), meta: { public: true, authPage: true, title: '登录' } },
  { path: '/register', name: 'Register', component: () => import('@/views/auth/RegisterView.vue'), meta: { public: true, authPage: true, title: '注册' } },
  { path: '/forgot-password', name: 'ForgotPassword', component: () => import('@/views/auth/ForgotPasswordView.vue'), meta: { public: true, authPage: true, title: '找回密码' } },
  { path: '/reset-password', name: 'ResetPassword', component: () => import('@/views/auth/ResetPasswordView.vue'), meta: { public: true, authPage: true, title: '重置密码' } },
  { path: '/auth-unavailable', name: 'AuthUnavailable', component: AuthUnavailableView, meta: { public: true, title: '认证服务暂不可用' } },
  { path: '/feature-unavailable', name: 'FeatureUnavailable', component: () => import('@/views/error/FeatureUnavailableView.vue'), meta: { public: true, title: '能力暂未开放' } },
  { path: '/403', name: 'Forbidden', component: () => import('@/views/error/ForbiddenView.vue'), meta: { public: true, title: '无权限' } },
  { path: '/404', name: 'NotFound', component: () => import('@/views/error/NotFoundView.vue'), meta: { public: true, title: '页面不存在' } },
  {
    path: '/',
    component: () => import('@/layouts/UserLayout.vue'),
    meta: { requiresAuth: true },
    children: [
      { path: '', redirect: '/dashboard' },
      { path: 'dashboard', name: 'Dashboard', component: () => import('@/views/user/JobCoachHomeView.vue'), meta: { title: '工作台' } },
      { path: 'onboarding', name: 'UserOnboarding', component: () => import('@/views/user/UserOnboardingView.vue'), meta: { title: '新手引导' } },
      { path: 'dashboard/v3', name: 'V3Dashboard', component: () => import('@/views/v3/V3DashboardView.vue'), meta: { title: '求职驾驶舱', hidden: true, commandHidden: true } },
      { path: 'profile', name: 'Profile', component: () => import('@/views/user/ProfileView.vue'), meta: { title: '个人资料' } },
      { path: 'password', name: 'Password', component: () => import('@/views/user/PasswordView.vue'), meta: { title: '修改密码' } },
      { path: 'notifications', name: 'Notifications', component: () => import('@/views/user/NotificationCenterView.vue'), meta: { title: '通知中心' } },
      { path: 'weakness-analysis', name: 'WeaknessAnalysis', component: () => import('@/views/user/WeaknessAnalysisView.vue'), meta: { title: '薄弱点分析' } },
      { path: 'projects', name: 'ProjectExperience', component: () => import('@/views/user/ProjectExperienceView.vue'), meta: { title: '项目经历' } },
      { path: 'questions', name: 'QuestionList', component: () => import('@/views/question/QuestionListView.vue'), meta: { title: '题库' } },
      { path: 'questions/practice', name: 'QuestionPractice', component: () => import('@/views/question/QuestionPracticeSessionView.vue'), meta: { title: '专项练习' } },
      { path: 'questions/wrong-records', name: 'WrongQuestions', component: () => import('@/views/question/WrongQuestionView.vue'), meta: { title: '错题本' } },
      { path: 'questions/favorites', name: 'FavoriteQuestions', component: () => import('@/views/question/FavoriteQuestionView.vue'), meta: { title: '收藏题目' } },
      { path: 'questions/recommendations', name: 'QuestionRecommendations', component: () => import('@/views/question/QuestionTrainingHubView.vue'), meta: { title: '题库' } },
      { path: 'questions/:id', name: 'QuestionDetail', component: () => import('@/views/question/QuestionTrainingDetailView.vue'), meta: { title: '答题训练' } },
      { path: 'job-targets', name: 'JobTargets', component: () => import('@/views/v3/JobTargetListView.vue'), meta: { title: '岗位目标' } },
      { path: 'job-targets/create', name: 'JobTargetCreate', component: () => import('@/views/v3/JobTargetEditView.vue'), meta: { title: '新建岗位目标' } },
      { path: 'job-targets/:id/edit', name: 'JobTargetEdit', component: () => import('@/views/v3/JobTargetEditView.vue'), meta: { title: '编辑岗位目标' } },
      { path: 'job-targets/:id/analysis', name: 'JobTargetAnalysis', component: () => import('@/views/v3/JobTargetAnalysisView.vue'), meta: { title: '岗位分析' } },
      { path: 'resumes', name: 'ResumeJobHub', component: () => import('@/views/resume/ResumeJobHubView.vue'), meta: { title: '简历实验' } },
      { path: 'resumes/manage', name: 'ResumeList', component: () => import('@/views/resume/ResumeListView.vue'), meta: { title: '简历列表' } },
      { path: 'resumes/create', name: 'ResumeCreate', component: () => import('@/views/resume/ResumeEditView.vue'), meta: { title: '新建简历' } },
      { path: 'resumes/:id/edit', name: 'ResumeEdit', component: () => import('@/views/resume/ResumeEditView.vue'), meta: { title: '编辑简历' } },
      { path: 'resumes/:id/versions', name: 'ResumeVersionsByResume', component: () => import('@/views/v4/ResumeVersionView.vue'), meta: { title: '简历版本', previewOnly: true } },
      { path: 'project-evidence', name: 'ProjectEvidenceList', component: () => import('@/views/project-evidence/ProjectEvidenceListView.vue'), meta: { title: '项目素材' } },
      { path: 'project-evidence/create', name: 'ProjectEvidenceCreate', component: () => import('@/views/project-evidence/ProjectEvidenceEditView.vue'), meta: { title: '新建项目素材' } },
      { path: 'project-evidence/:id', name: 'ProjectEvidenceDetail', component: () => import('@/views/project-evidence/ProjectEvidenceDetailView.vue'), meta: { title: '项目素材详情' } },
      { path: 'project-evidence/:id/edit', name: 'ProjectEvidenceEdit', component: () => import('@/views/project-evidence/ProjectEvidenceEditView.vue'), meta: { title: '编辑项目素材' } },
      { path: 'resume-match', name: 'ResumeMatch', component: () => import('@/views/v3/ResumeMatchView.vue'), meta: { title: '简历匹配' } },
      { path: 'resume-match/:id', name: 'ResumeMatchDetail', component: () => import('@/views/v3/ResumeMatchDetailView.vue'), meta: { title: '简历匹配详情' } },
      { path: 'resume-job-match', redirect: '/resume-match', meta: { hidden: true, commandHidden: true } },
      { path: 'resume-job-match/:id', redirect: (to) => ({ name: 'ResumeMatchDetail', params: to.params }), meta: { hidden: true, commandHidden: true } },
      { path: 'skill-profile', name: 'SkillProfile', component: () => import('@/views/v3/SkillProfileView.vue'), meta: { title: '能力画像' } },
      { path: 'ability-map', name: 'AbilityMap', component: () => import('@/views/ability-map/AbilityMapView.vue'), meta: { title: '能力图谱' } },
      { path: 'interviews/create', name: 'InterviewCreate', component: () => import('@/views/interview/InterviewCreateView.vue'), meta: { title: '创建面试' } },
      { path: 'interviews/room/:id', name: 'InterviewRoom', component: () => import('@/views/interview/InterviewRoomView.vue'), meta: { title: '面试房间' } },
      { path: 'interviews/history', name: 'InterviewHistory', component: () => import('@/views/interview/InterviewHistoryView.vue'), meta: { title: '面试历史' } },
      { path: 'interviews/:id', name: 'InterviewDetail', component: () => import('@/views/interview/InterviewDetailView.vue'), meta: { title: '面试详情' } },
      { path: 'interviews/:id/report', name: 'InterviewReport', component: () => import('@/views/interview/InterviewReportView.vue'), meta: { title: '面试报告' } },
      { path: 'study-plans/from-gap', name: 'StudyPlansFromGap', component: () => import('@/views/v3/StudyPlanFromGapView.vue'), meta: { title: '短板学习计划' } },
      { path: 'study-plans', name: 'StudyPlans', component: () => import('@/views/study/StudyPlanView.vue'), meta: { title: '学习计划' } },
      { path: 'daily-tasks', name: 'DailyTasks', component: () => import('@/views/study/DailyTaskView.vue'), meta: { title: '每日任务' } },
      { path: 'tools', name: 'RecordsTools', component: () => import('@/views/tools/RecordsToolsView.vue'), meta: { title: '记录与工具' } },
      { path: 'offer-help', redirect: '/tools', meta: { hidden: true } },
      { path: 'analytics/personal', name: 'PersonalAnalytics', component: () => import('@/views/analytics/PersonalAnalyticsView.vue'), meta: { title: '训练分析' } },
      { path: 'agent/reviews', name: 'AgentReviews', component: () => import('@/views/v4/AgentReviewView.vue'), meta: { title: '每日复盘', previewOnly: true } },
      { path: 'growth/profile', name: 'GrowthProfile', component: () => import('@/views/v4/GrowthProfileView.vue'), meta: { title: '成长画像', previewOnly: true } },
      { path: 'growth/skills', name: 'GrowthSkillsTrend', component: () => import('@/views/v4/GrowthProfileView.vue'), meta: { title: '技能趋势', previewOnly: true } },
      { path: 'growth/readiness', name: 'GrowthReadinessTrend', component: () => import('@/views/v4/GrowthProfileView.vue'), meta: { title: '就绪度趋势', previewOnly: true } },
      { path: 'agent/memory', name: 'AgentMemory', component: () => import('@/views/v4/AgentMemoryView.vue'), meta: { title: '长期记忆', previewOnly: true } },
      { path: 'knowledge', name: 'PersonalKnowledgeBase', component: () => import('@/views/v4/KnowledgeBaseView.vue'), meta: { title: '个人知识库', previewOnly: true } },
      { path: 'resume-versions', name: 'ResumeVersions', component: () => import('@/views/v4/ResumeVersionView.vue'), meta: { title: '简历版本', previewOnly: true } },
      { path: 'applications', name: 'JobApplications', component: () => import('@/views/v4/JobApplicationView.vue'), meta: { title: '投递管理', previewOnly: true } },
      { path: 'agent/today', name: 'AgentToday', component: () => import('@/views/agent/AgentTodayView.vue'), meta: { title: '今日任务' } },
      { path: 'agent/tasks', name: 'AgentTasks', component: () => import('@/views/agent/AgentTaskListView.vue'), meta: { title: '任务中心' } },
      { path: 'job-experiments', name: 'JobExperiments', component: () => import('@/views/job-experiment/JobExperimentListView.vue'), meta: { title: '求职实验台' } },
      { path: 'job-experiments/create', name: 'JobExperimentCreate', component: () => import('@/views/job-experiment/JobExperimentCreateView.vue'), meta: { title: '新建求职实验' } },
      { path: 'job-experiments/:id/edit', name: 'JobExperimentEdit', component: () => import('@/views/job-experiment/JobExperimentCreateView.vue'), meta: { title: '编辑求职实验' } },
      { path: 'job-experiments/:id/review', name: 'JobExperimentReview', component: () => import('@/views/job-experiment/JobExperimentReviewView.vue'), meta: { title: '求职实验复盘' } },
      { path: 'job-experiments/:id', name: 'JobExperimentDetail', component: () => import('@/views/job-experiment/JobExperimentDetailView.vue'), meta: { title: '求职实验详情' } },
      { path: 'portfolio-demo', name: 'PortfolioDemo', component: () => import('@/views/portfolio-demo/PortfolioDemoView.vue'), meta: { title: '作品集演示模式' } },
      { path: 'agent/runs/:id', name: 'AgentRunDetail', component: () => import('@/views/agent/AgentRunDetailView.vue'), meta: { title: '生成详情' } }
    ]
  },
  {
    path: '/admin',
    component: () => import('@/layouts/AdminLayout.vue'),
    meta: { requiresAuth: true, requiresAdmin: true, title: '管理后台' },
    children: [
      { path: 'dashboard', name: 'AdminDashboard', component: () => import('@/views/admin/AdminDashboardView.vue'), meta: { title: '运营首页', icon: 'DataBoard', requiredPermissions: ['admin:system:overview'] } },
      { path: 'users', name: 'AdminUsers', component: () => import('@/views/admin/UserManageView.vue'), meta: { title: '用户管理', icon: 'UserFilled', requiredPermissions: ['admin:user:list'] } },
      { path: 'roles', name: 'AdminRoles', component: () => import('@/views/admin/RoleManageView.vue'), meta: { title: '角色管理', icon: 'Connection', requiredPermissions: ['admin:role:list'] } },
      { path: 'questions', name: 'AdminQuestions', component: () => import('@/views/admin/QuestionManageView.vue'), meta: { title: '题目管理', icon: 'Collection', requiredPermissions: ['admin:question:list'] } },
      { path: 'ai/questions/generate', name: 'AdminAiQuestionGenerate', component: () => import('@/views/admin/QuestionManageView.vue'), props: { initialGovernanceTab: 'generate', governanceOnly: true }, meta: { title: 'AI 题目生成', icon: 'Operation', requiredPermissions: ['admin:question:generate'] } },
      { path: 'question-reviews', name: 'AdminQuestionReviews', component: () => import('@/views/admin/QuestionManageView.vue'), props: { initialGovernanceTab: 'reviews', governanceOnly: true }, meta: { title: '题目审核', icon: 'DataAnalysis', requiredPermissions: ['admin:question:review'] } },
      { path: 'question-review', redirect: '/admin/question-reviews', meta: { hidden: true } },
      { path: 'question-duplicate-reviews', name: 'AdminQuestionDuplicateReviews', component: () => import('@/views/admin/QuestionDuplicateReviewView.vue'), meta: { title: '题目去重审核', icon: 'Connection', requiredPermissions: ['admin:question:dedupe'] } },
      { path: 'question-duplicates', redirect: '/admin/question-duplicate-reviews', meta: { hidden: true } },
      { path: 'question-relations', name: 'AdminQuestionRelations', component: () => import('@/views/admin/QuestionRelationManageView.vue'), meta: { title: '题目关系', icon: 'Share', requiredPermissions: ['admin:question:relation'] } },
      { path: 'question-categories', name: 'AdminQuestionCategories', component: () => import('@/views/admin/QuestionCategoryManageView.vue'), meta: { title: '分类管理', icon: 'Files', requiredPermissions: ['admin:question:category'] } },
      { path: 'question-tags', name: 'AdminQuestionTags', component: () => import('@/views/admin/QuestionTagManageView.vue'), meta: { title: '标签管理', icon: 'PriceTag', requiredPermissions: ['admin:question:tag'] } },
      { path: 'question-groups', name: 'AdminQuestionGroups', component: () => import('@/views/admin/QuestionGroupManageView.vue'), meta: { title: '问题组管理', icon: 'List', requiredPermissions: ['admin:question:group'] } },
      { path: 'industry-templates', name: 'AdminIndustryTemplates', component: () => import('@/views/admin/IndustryTemplateManageView.vue'), meta: { title: '行业模板', icon: 'List', requiredPermissions: ['admin:industry-template:list'] } },
      { path: 'files', name: 'AdminFiles', component: () => import('@/views/admin/AdminFileManageView.vue'), meta: { title: '文件治理', icon: 'Folder', requiredPermissions: ['admin:file:list'] } },
      { path: 'ai/prompts', name: 'AdminAiPrompts', component: () => import('@/views/admin/PromptTemplateView.vue'), meta: { title: '提示词模板', icon: 'Operation', requiredPermissions: ['admin:ai:prompt:list'] } },
      { path: 'agent/prompts', redirect: '/admin/ai/prompts', meta: { hidden: true } },
      { path: 'ai/logs', name: 'AdminAiLogs', component: () => import('@/views/admin/AiCallLogView.vue'), meta: { title: 'AI 运行记录', icon: 'DataAnalysis', requiredPermissions: ['admin:ai:log:list'] } },
      { path: 'ai/models', name: 'AdminAiModels', component: () => import('@/views/admin/AiModelConfigView.vue'), meta: { title: 'AI 模型配置', icon: 'Operation', requiredPermissions: ['admin:ai:model:list'] } },
      { path: 'system/configs', name: 'AdminSystemConfigs', component: () => import('@/views/admin/SystemConfigView.vue'), meta: { title: '系统配置', icon: 'Setting', requiredPermissions: ['admin:system:config:list'] } },
      { path: 'system-config', redirect: '/admin/system/configs', meta: { hidden: true } },
      { path: 'menus', name: 'AdminMenus', component: () => import('@/views/admin/MenuPermissionView.vue'), meta: { title: '菜单权限', icon: 'Lock', requiredPermissions: ['admin:menu:list'] } },
      { path: 'permissions', redirect: '/admin/menus', meta: { hidden: true } },
      { path: 'notices', name: 'AdminNotices', component: () => import('@/views/admin/NotificationManageView.vue'), meta: { title: '通知管理', icon: 'Bell', requiredPermissions: ['admin:notice:list'] } },
      { path: 'announcements', name: 'AdminAnnouncements', component: () => import('@/views/admin/AnnouncementManageView.vue'), meta: { title: '公告管理', icon: 'Bell', requiredPermissions: ['admin:announcement:list'] } },
      { path: 'notifications', redirect: '/admin/notices', meta: { hidden: true } },
      { path: 'operation-logs', name: 'AdminOperationLogs', component: () => import('@/views/admin/OperationLogView.vue'), meta: { title: '操作日志', icon: 'Document', requiredPermissions: ['admin:audit:operation-log'] } },
      { path: 'logs/operations', redirect: '/admin/operation-logs', meta: { hidden: true } },
      { path: 'logs/summary', redirect: '/admin/operation-logs', meta: { hidden: true } },
      { path: 'login-logs', name: 'AdminLoginLogs', component: () => import('@/views/admin/LoginLogView.vue'), meta: { title: '登录日志', icon: 'Key', requiredPermissions: ['admin:audit:login-log'] } },
      { path: 'slow-sql-logs', name: 'AdminSlowSqlLogs', component: () => import('@/views/admin/SlowSqlLogView.vue'), meta: { title: '慢 SQL 查询', icon: 'DataAnalysis', requiredPermissions: ['admin:audit:slow-sql-log'] } },
      { path: 'logs/slow-sql', redirect: '/admin/slow-sql-logs', meta: { hidden: true } },
      { path: 'slow-sql', redirect: '/admin/slow-sql-logs', meta: { hidden: true } },
      { path: 'interviews', name: 'AdminInterviews', component: () => import('@/views/admin/InterviewManageView.vue'), meta: { title: '面试记录', icon: 'ChatDotRound', requiredPermissions: ['admin:interview:list'] } },
      { path: 'interview-reports', name: 'AdminInterviewReports', component: () => import('@/views/admin/InterviewReportManageView.vue'), meta: { title: '面试报告', icon: 'Document', requiredPermissions: ['admin:interview:report'] } },
      { path: 'analytics/agent', name: 'AdminAgentAnalytics', component: () => import('@/views/admin/AdminAgentAnalyticsView.vue'), meta: { title: '生成效果分析', icon: 'DataAnalysis', requiredPermissions: ['admin:analytics:agent'] } },
      { path: 'agent/analytics', redirect: '/admin/analytics/agent', meta: { hidden: true } },
      { path: 'analytics/overview', redirect: '/admin/analytics/agent', meta: { hidden: true } },
      { path: 'analytics/training', redirect: '/admin/analytics/agent', meta: { hidden: true } },
      { path: 'analytics/ai', name: 'AdminAiOpsAnalytics', component: () => import('@/views/admin/AdminAiOpsAnalyticsView.vue'), meta: { title: 'AI 运营看板', icon: 'DataAnalysis', requiredPermissions: ['admin:analytics:ai'] } },
      { path: 'ai/feedback', redirect: '/admin/analytics/ai', meta: { hidden: true } },
      { path: 'ops/overview', name: 'AdminOpsOverview', component: () => import('@/views/admin/AdminOpsOverviewView.vue'), meta: { title: '运维总览', hidden: true, requiredPermissions: ['admin:analytics:ai'] } },
      { path: 'ai/ops', redirect: '/admin/ops/overview', meta: { hidden: true } },
      { path: 'knowledge', redirect: '/admin/ops/overview', meta: { hidden: true } },
      { path: 'vector-indexes', redirect: '/admin/ops/overview', meta: { hidden: true } },
      { path: 'analytics/metrics', name: 'AdminAnalyticsMetrics', component: () => import('@/views/admin/AdminAnalyticsMetricsView.vue'), meta: { title: '指标字典', icon: 'DataAnalysis', requiredPermissions: ['admin:analytics:agent'] } },
      { path: 'metrics', redirect: '/admin/analytics/metrics', meta: { hidden: true } },
      { path: 'analytics/jobs', name: 'AdminAnalyticsJobs', component: () => import('@/views/admin/AdminAnalyticsJobsView.vue'), meta: { title: '聚合任务', icon: 'Timer', requiredPermissions: ['admin:analytics:agent'] } },
      { path: 'scheduler', redirect: '/admin/analytics/jobs', meta: { hidden: true } },
      { path: 'ai/prompt-regression', name: 'AdminPromptRegression', component: () => import('@/views/admin/AdminPromptRegressionView.vue'), meta: { title: '提示词回归', icon: 'Operation', requiredPermissions: ['admin:agent:prompt-regression:list'] } },
      { path: 'agent/runs', name: 'AdminAgentRuns', component: () => import('@/views/admin/AdminAgentRunView.vue'), meta: { title: '生成运行记录', icon: 'DataAnalysis', requiredPermissions: ['admin:agent:run:list'] } },
      { path: 'agent-runs', redirect: '/admin/agent/runs', meta: { hidden: true } },
      { path: 'agent/tasks', name: 'AdminAgentTasks', component: () => import('@/views/admin/AdminAgentTaskView.vue'), meta: { title: '生成任务处理', icon: 'Timer', requiredPermissions: ['admin:agent:task:list'] } },
      { path: 'agent-tasks', redirect: '/admin/agent/tasks', meta: { hidden: true } },
      { path: 'async-tasks', name: 'AdminAsyncTasks', component: () => import('@/views/admin/AsyncTaskView.vue'), meta: { title: '任务中心', icon: 'Timer', requiredPermissions: ['admin:task:list'] } },
      { path: 'dead-letters', redirect: { path: '/admin/async-tasks', query: { status: 'DEAD_LETTER' } }, meta: { hidden: true } },
      { path: 'tasks', redirect: '/admin/async-tasks', meta: { hidden: true } },
      { path: 'system-configs', redirect: '/admin/system/configs', meta: { hidden: true } },
      { path: 'configs', redirect: '/admin/system/configs', meta: { hidden: true } }
    ]
  },
  { path: '/:pathMatch(.*)*', redirect: '/404' }
]
